### ISSUE TITLE
Not working on gnome-shell 3.28.4

### ISSUE THREAD

**Issue by pawelkarauda** [bsaleil/todolist-gnome-shell-extension#57]
Hello :) 

I really like this extension and would love to make it work on my computer!

When I try to install it via Gnome Shell extensions page I receive:
![image](https://user-images.githubusercontent.com/30434886/79538254-4d59f180-8084-11ea-9d27-ba2fbce70ae8.png)

I also tried this solution from comments:
![image](https://user-images.githubusercontent.com/30434886/79538291-5fd42b00-8084-11ea-8286-c350f43afd6c.png)

But after restart of gnome it still doesn't appear in right corner

**Comment by bsaleil** [comment]
@pawelkarauda I'm closing it since 3.28 is now relatively old and the extension is reported to work on newer versions of gnome-shell. It is recommended to follow the manual installation instructions to install the extension: https://github.com/bsaleil/todolist-gnome-shell-extension/blob/master/README.md.
